import AsyncStorage from '@react-native-async-storage/async-storage';
// @ts-expect-error generated by `withStorybook` when Metro bundles this config folder
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
